apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
        - name: rust-api
          image: ghcr.io/nerif-tafu/rust-api:v1.0.0 # {"$imagepolicy": "flux-system:rust-api"}
          ports:
            - containerPort: 3100
          env:
            - name: STEAM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rust-api-steam
                  key: STEAM_USERNAME
            - name: STEAM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rust-api-steam
                  key: STEAM_PASSWORD
            - name: STEAM_APP_ID
              valueFrom:
                secretKeyRef:
                  name: rust-api-steam
                  key: STEAM_APP_ID
