apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-api
  namespace: rust-api
  labels:
    traefik.tafu.casa/instance: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik-public
  rules:
    - host: rust-api.tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rust-api
                port:
                  number: 80
  tls:
    - hosts:
        - rust-api.tafu.casa
      secretName: rust-api-tls
