
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./shorturl
  - ./rust-api
  - ./rust-plus-provider
  - ./pipe-dreams
  - ./rust-booter
  - ./rustplus-shop-helper-v2
  - ./fitv2
  - ./vocard
  - ./wg-easy
  - ./tafu-casa
  - ./microbin
  - ./filebrowser
