apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaresolverr
  namespace: media
  labels:
    traefik.tafu.casa/instance: internal
spec:
  ingressClassName: traefik-internal
  tls:
    - hosts:
        - flaresolverr.cl.tafu.casa
      secretName: wildcard-cl-tafu-casa-tls
  rules:
    - host: flaresolverr.cl.tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flaresolverr
                port:
                  number: 8191
