apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - wildcard-cert.yaml
  - ./plex
  - ./prowlarr
  - ./sonarr
  - ./radarr
  - ./bazarr
  - ./flaresolverr
  - ./overseerr
  - ./qbittorrent
