apiVersion: v1
kind: Service
metadata:
  name: rustplus-shop-helper-v2
  namespace: rustplus-shop-helper-v2
spec:
  selector:
    app: rustplus-shop-helper-v2
  ports:
    - port: 80
      targetPort: 3001
