apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: wg-easy
  namespace: traefik
  labels:
    traefik.tafu.casa/instance: public
spec:
  entryPoints:
    - wireguard
  routes:
    - services:
        - name: wg-easy
          namespace: wg-easy
          port: 51820
