apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitv2
  namespace: fitv2
  labels:
    traefik.tafu.casa/instance: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik-public
  rules:
    - host: fit.tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fitv2
                port:
                  number: 80
  tls:
    - hosts:
        - fit.tafu.casa
      secretName: fitv2-tls
