apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wg-easy
  namespace: traefik
  labels:
    traefik.tafu.casa/instance: internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vpn.cl.tafu.casa`)
      kind: Rule
      services:
        - name: wg-easy
          namespace: wg-easy
          port: 51821
  tls:
    secretName: wildcard-cl-tafu-casa-tls
