apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
  namespace: shorturl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
        - name: shorturl
          image: ghcr.io/nerif-tafu/shorturl:latest
          ports:
            - containerPort: 3000
