apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
  namespace: shorturl
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
        - name: shorturl
          image: ghcr.io/nerif-tafu/shorturl:v1.0.0 # {"$imagepolicy": "flux-system:shorturl"}
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: shorturl-data
