apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-public
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "26.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.3.61
    providers:
      kubernetesCRD:
        labelSelector: "traefik.tafu.casa/instance=public"
      kubernetesIngress:
        labelSelector: "traefik.tafu.casa/instance=public"
    ingressRoute:
      dashboard:
        labels:
          traefik.tafu.casa/instance: public
