apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease-internal.yaml
  - helmrelease-public.yaml
  - wildcard-cert.yaml
  - traefik-public-dashboard-service.yaml
  - dashboard-ingressroute.yaml
  - routes
