apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cl-tafu-casa
  namespace: traefik
spec:
  secretName: wildcard-cl-tafu-casa-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.cl.tafu.casa"
