apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ghcr-registry-secret.yaml
  - shorturl-imagerepository.yaml
  - shorturl-imagepolicy.yaml
  - rust-api-imagerepository.yaml
  - rust-api-imagepolicy.yaml
  - rust-plus-provider-imagerepository.yaml
  - rust-plus-provider-imagepolicy.yaml
  - pipe-dreams-imagerepository.yaml
  - pipe-dreams-imagepolicy.yaml
  - rust-booter-imagerepository.yaml
  - rust-booter-imagepolicy.yaml
  - rustplus-shop-helper-v2-imagerepository.yaml
  - rustplus-shop-helper-v2-imagepolicy.yaml
  - fitv2-imagerepository.yaml
  - fitv2-imagepolicy.yaml
  - vocard-imagerepository.yaml
  - vocard-imagepolicy.yaml
  - vocard-dashboard-imagerepository.yaml
  - vocard-dashboard-imagepolicy.yaml
  - lavalink-imagerepository.yaml
  - lavalink-imagepolicy.yaml
  - spotify-tokener-imagerepository.yaml
  - spotify-tokener-imagepolicy.yaml
  - yt-cipher-imagerepository.yaml
  - yt-cipher-imagepolicy.yaml
  - imageupdateautomation.yaml
