apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - shorturl-imagerepository.yaml
  - shorturl-imagepolicy.yaml
  - rust-api-imagerepository.yaml
  - rust-api-imagepolicy.yaml
  - rust-plus-provider-imagerepository.yaml
  - rust-plus-provider-imagepolicy.yaml
  - pipe-dreams-imagerepository.yaml
  - pipe-dreams-imagepolicy.yaml
  - imageupdateautomation.yaml
