apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-booter
  namespace: rust-booter
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app: rust-booter
  template:
    metadata:
      labels:
        app: rust-booter
    spec:
      containers:
        - name: rust-booter
          image: ghcr.io/nerif-tafu/rust-booter:v1.0.0 # {"$imagepolicy": "flux-system:rust-booter"}
          ports:
            - containerPort: 8534
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rust-booter-data
