apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-booter
  namespace: rust-booter
  labels:
    traefik.tafu.casa/instance: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik-public
  rules:
    - host: rooster.tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rust-booter
                port:
                  number: 80
  tls:
    - hosts:
        - rooster.tafu.casa
      secretName: rust-booter-tls
