apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vocard-db-pvc.yaml
  - vocard-db-secret.yaml
  - vocard-db-deployment.yaml
  - lavalink-configmap.yaml
  - lavalink-pvc.yaml
  - lavalink-secret.yaml
  - lavalink-deployment.yaml
  - spotify-tokener-deployment.yaml
  - yt-cipher-deployment.yaml
  - vocard-settings-secret.yaml
  - vocard-deployment.yaml
  - vocard-dashboard-settings-secret.yaml
  - vocard-dashboard-deployment.yaml
