apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tafu-casa
  namespace: tafu-casa
  labels:
    traefik.tafu.casa/instance: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik-public
  rules:
    - host: tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tafu-casa
                port:
                  number: 80
  tls:
    - hosts:
        - tafu.casa
      secretName: tafu-casa-tls
