apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbin
  namespace: microbin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: microbin
  template:
    metadata:
      labels:
        app: microbin
    spec:
      containers:
        - name: microbin
          image: docker.io/danielszabo99/microbin:2.1.0 # {"$imagepolicy": "flux-system:microbin"}
          envFrom:
            - secretRef:
                name: microbin-auth
          env:
            - name: MICROBIN_DATA_DIR
              value: "/data"
            - name: MICROBIN_PORT
              value: "8080"
            - name: MICROBIN_BIND
              value: "0.0.0.0"
            - name: MICROBIN_PUBLIC_PATH
              value: "https://paste.tafu.casa/"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: microbin-data
