apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microbin
  namespace: microbin
  labels:
    traefik.tafu.casa/instance: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik-public
  rules:
    - host: paste.tafu.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microbin
                port:
                  number: 80
  tls:
    - hosts:
        - paste.tafu.casa
      secretName: microbin-tls
